### ISSUE TITLE
`descriptionColor` is unused

### ISSUE THREAD

**Issue by davesmith00000** [reibitto/sbt-welcome#2]
Setting `descriptionColor` does nothing, a glance over the codebase suggests the value isn't in use?

**Comment by reibitto** [comment]
Oops, I don't know how I missed that. Thanks! I'll fix that today.

**Comment by reibitto** [comment]
The fix for this in, but releasing might take a while. I might have to migrate to the new Sonatype host due to all the timeouts, but let me give it a try first.

**Comment by reibitto** [comment]
ok, looks like the release worked. I guess Sonatype isn't busy this time of day (and it's still Sunday most places).
