### ISSUE TITLE
Auto-bullets for aliases

### ISSUE THREAD

**Issue by davesmith00000** [reibitto/sbt-welcome#5]
Currently you have to set the alias values yourself, which is ok, but it's very easy to make a mistake.

If I have a welcome config like:

```
UsefulTask("a", "clean", "...")
UsefulTask("b", "test", "...")
UsefulTask("c", "publishLocal", "...")
```
and then I realise I forgot `compile` (in this contrived example), there is nothing stopping me doing this:

```
UsefulTask("a", "clean", "...")
UsefulTask("b", "compile", "...")
UsefulTask("b", "test", "...")
UsefulTask("c", "publishLocal", "...")
```

Now I have two b's!

It would be nice if there was a construct that organised the aliases for me, so they are sequential and unique.

**Comment by reibitto** [comment]
That's a good point. I think an auto-increment like that would be useful. I'm not quite sure how to model that currently, but maybe I need to make `alias` a proper ADT rather than just `String`?

Or maybe I can add a Config case class and add a new sbt setting for it.
